export default function(text: string) {
	return text
		.replace(/\[\[[Aa]bilities\|ability]]/g, '[[ability]]')
		.replace(/\[\[[Aa]bilities\|Ability]]/g, '[[Ability]]')
		.replace(/\[\[[Aa]ccounts\|account]]/g, '[[account]]')
		.replace(/\[\[[Aa]ccounts\|Account]]/g, '[[Account]]')
		.replace(/\[\[[Cc]olors\|color]]/g, '[[color]]')
		.replace(/\[\[[Cc]olors\|Color]]/g, '[[Color]]')
		.replace(/\[\[[Dd]oors\|door]]/g, '[[door]]')
		.replace(/\[\[[Dd]oors\|Door]]/g, '[[Door]]')
		.replace(/\[\[[Ee]jection\|ejected]]/g, '[[eject]]ed')
		.replace(/\[\[[Ee]jection\|Ejected]]/g, '[[Eject]]ed')
		.replace(/\[\[[Hh]ats\|hat]]/g, '[[hat]]')
		.replace(/\[\[[Hh]ats\|Hat]]/g, '[[Hat]]')
		.replace(/\[\[[Ll]obby\|lobbies]]/g, '[[lobbies]]')
		.replace(/\[\[[Ll]obby\|Lobbies]]/g, '[[Lobbies]]')
		.replace(/\[\[[Ll]ocations\|location]]/g, '[[location]]')
		.replace(/\[\[[Ll]ocations\|Location]]/g, '[[Location]]')
		.replace(/\[\[[Mm]aps\|map]]/g, '[[map]]')
		.replace(/\[\[[Mm]aps\|Map]]/g, '[[Map]]')
		.replace(/\[\[[Oo]ptions\|option]]/g, '[[option]]')
		.replace(/\[\[[Mm]ptions\|Option]]/g, '[[Option]]')
		.replace(/\[\[[Pp]ets\|pet]]/g, '[[pet]]')
		.replace(/\[\[[Pp]ets\|Pet]]/g, '[[Pet]]')
		.replace(/\[\[[Rr]oles\|role]]/g, '[[role]]')
		.replace(/\[\[[Rr]oles\|Role]]/g, '[[Role]]')
		.replace(/\[\[[Ss]kins\|skin]]/g, '[[skin]]')
		.replace(/\[\[[Ss]kins\|Skin]]/g, '[[Skin]]')
		.replace(/\[\[[Tt]asks\|task]]/g, '[[task]]')
		.replace(/\[\[[Tt]asks\|Task]]/g, '[[Task]]')
		.replace(/\[\[[Vv]isual tasks\|visual task]]/g, '[[visual task]]')
		.replace(/\[\[[Vv]isual tasks\|Visual task]]/g, '[[Visual task]]')
		// Alternate names
		.replace(/\[\[Divert Power\|Accept Diverted Power]]/g, '[[Accept Diverted Power]]')
		.replace(/\[\[Upload Data\|Download Data]]/g, '[[Download Data]]')
		.replace(/\[\[Empty Garbage\|Empty Chute]]/g, '[[Empty Chute]]')
}

export let summary = 'fixing links';